### ISSUE TITLE
Input word "a$$" causing false positives in the Regex

### ISSUE THREAD

**Issue by lostpebble** [2Toad/Profanity#18]
Hi there, thanks for this library.

I was just running it through an ID generator today to test it out, and printed out when it found an ID containing a bad word- these were some of the IDs it found (I'm using wholeWord=false ):

(I can't see any profanity here:)

```
MPEUGNMA
68Q56K5A
FCHZ6ZHA
UF7622DA
98AS3KVA
VFR9D5WA
4YX5AWVA
YVMNJU9A
DP4NMN8A
9PJMLM6A
ZNIVMM3A
XJMZC24A
```

These it found, which I can clearly see the profanity:

```
FFP7YFAG
S6FASSYJ
```

After writing this issue now, I can clearly see a pattern emerging. I think there is an issue happening with the input of the text from the file into the regex creation, which is causing one of the rules to include anything which ends with the letter `A`.

This might be the culprit: `a$$`- since `$` represents "end of word" in regex.

---

In fact, I can confirm that, once I manually removed it from the words.txt file - I am not getting those false positives anymore.

**Comment by lostpebble** [comment]
I think it might be useful to run a function like this over each line in the profanity list to be sure its all escaped:

```ts
function escapeRegExp(string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
}
```

Eg.:

```
escapeRegExp("All of these should be escaped: \ ^ $ * + ? . ( ) | { } [ ]");

>>> "All of these should be escaped: \\ \^ \$ \* \+ \? \. \( \) \| \{ \} \[ \] "
```

Found here : https://stackoverflow.com/a/6969486/2172531

**Comment by JasonPierce** [comment]
@lostpebble thanks for reporting this. All help is appreciated, if you'd like to create a PR

**Comment by lostpebble** [comment]
No worries @JasonPierce , thanks for the lib. I made a pull request with the changes, and added a couple tests for this case as well.
