### ISSUE TITLE
Add whitelist

### ISSUE THREAD

**Issue by daneleo** [2Toad/Profanity#2]
could we get a black list command?

for example we keep 
options.wholeWord = false;
but for example 
someone says 'cock' fair enough it censors it, but if someone says cockpit then it sensors it again
we want to keep the wholeWord to false as its a lot easier to mange than inserting every bit of word in to the file, is this possible?
Thanks, Dane

**Comment by JasonPierce** [comment]
@daneleo thanks for the suggestion. I believe what you're asking for is a whitelist (aka, words that are never flagged as profanity). The [words.txt](https://github.com/2Toad/Profanity/blob/master/src/words.txt) file that drives the `profanity` lib is essentially a blacklist.

This is a great suggestion.

**Comment by daneleo** [comment]
You're very welcome! Always wanting to help out! Plus we use use this for my discord bot for our space engineers servers. So it would be great to use

**Comment by JasonPierce** [comment]
@daneleo sounds like you've found a very cool use for it, with that bot. FYI: this feature was released in v1.1.0, and is now available on NPM.

Incidentally, v1.1.0 also includes a fix for that blank line issue you just mentioned (see Issue #3).
