### ISSUE TITLE
npm package won't install for version 2.0.0

### ISSUE THREAD

**Issue by swatson12** [2Toad/Profanity#29]
The latest version won't install, it seems to be missing the entirety of the source code folder in the install

**Comment by JasonPierce** [comment]
Thanks for reporting this @swatson12 . Looking into it!

**Comment by JasonPierce** [comment]
Appears the 2.0.0 publish to NPM had an issue with the build, so the dist folder did not get included in the tarball that was published to NPM. I'm going to add a `prepublishOnly` script to the package to prevent this from happening during future deployments

**Comment by swatson12** [comment]
Thanks so much! 😁
