### ISSUE TITLE
Relax package engine Node version requirement

### ISSUE THREAD

**Issue by BearJS** [2Toad/Profanity#9]
Hi, I recently started using Profanity and think it is great. 

I have an issue with the explicitly set Node engine in the package.json. Currently, it is set to `"node": "14.15.0"` and it is causing issues in my environment which is running Node 15. 

`error @2toad/profanity@1.2.0: The engine "node" is incompatible with this module. Expected version "14.15.0". Got "15.2.0"
`

Currently, each time I run `yarn add` I have to put a flag to `--ignore-engines` to install properly. 

Please can you set this to be Node 14 and above rather than the current version?

**Comment by JasonPierce** [comment]
@BearJS I'm glad you are enjoying the lib. I have a [PR ](https://github.com/2Toad/Profanity/pull/11 )up to address your request.

Out of curiosity, which version of Yarn are you using? I'm testing with `yarn 1.22.10`, and it's installing without the error message you're reporting (or even a warning).
