### ISSUE TITLE
Add profane words for additional languages

### ISSUE THREAD

**Issue by JasonPierce** [2Toad/Profanity#92]
Profanity currently supports 4 languages: https://github.com/2Toad/Profanity/blob/master/supported-languages.md

| **Language** | **Locale** |
|--------------|------------|
| German       | `de`       |
| English      | `en`       |
| Spanish      | `es`       |
| French       | `fr`       |

- Create a script that generates profane words for other languages using the English word list and a translator service
- Generate the profane words and add them to ./data
- Update the Supported Languages doc

**Comment by konotorii** [comment]
Try [https://libretranslate.com/](https://libretranslate.com/), it's open source with multiple ways of self-hosting. Supports like over 20 languages. Could probably make a script to feed english swear swords to every other language and save results. I could probably do that if needed.

**Comment by JasonPierce** [comment]
Thanks for the suggestion @konotorii. What a great lib, especially since it can be self-hosted!

**Comment by JasonPierce** [comment]
Some thoughts on why I didn't include translations for every supported [languages](https://github.com/argosopentech/argos-translate/blob/master/argostranslate/languages.csv) in Libre Translate, now that I've configured it to generate the translations via an automated script: each additional language incorporated into the Profanity library increases the overall size of the library. To maintain performance and usability, I've limited translations to the following languages:

| **Language**         | **Locale** |
|-----------------------|------------|
| Arabic               | `ar`       |
| Chinese              | `zh`       |
| English              | `en`       |
| French               | `fr`       |
| German               | `de`       |
| Hindi                | `hi`       |
| Japanese             | `ja`       |
| Korean               | `ko`       |
| Portuguese           | `pt`       |
| Russian              | `ru`       |
| Spanish              | `es`       |

If you'd like to request a language not currently supported by Profanity, please submit your suggestion via our [GitHub issues page](https://github.com/2Toad/Profanity/issues). Keep in mind that Profanity's architecture already supports all languages through its [Customize Wordlist](https://github.com/2Toad/Profanity?tab=readme-ov-file#customize-the-word-list) feature, allowing you to add as many words or translations as you like during runtime.

**Comment by konotorii** [comment]
Maybe in the future it would be worthwhile to taken on a modular concept to only download and use the languages defined by the user/developer.
